### ISSUE TITLE
Status Code 204 not returning properly

### ISSUE THREAD

**Issue by mardix** [sparckles/Robyn#1009]
### Bug Description

Given a status code 204, it will not return properly. 

```
return Response(status_code=204, 
                     description=jsonify({...}), 
                     headers={"Content-Type": "application/json"})
```

As status code 204 is valid, how can we ensure any HTTP code get used used?

### Your operating system

MacOS

### Your Python version (`python --version`)

3.11

### Your Robyn version

latest

**Comment by VishnuSanal** [comment]
hi @mardix, thanks for reaching out! but I have some questions.

> it will not return properly

I didn't quite get this. from my initial testing, the following code seemed to work fine.

```
from robyn import Robyn, Response, jsonify

app = Robyn(__file__)


@app.get("/")
def h():
    return Response(
        status_code=204,
        description=jsonify({}),
        headers={"Content-Type": "application/json"}
    )


if __name__ == "__main__":
    app.start()
```

can you elaborate a bit on the issue and/or show us the code? thanks.

**Comment by sansyrox** [comment]
Hey @mardix 👋 

Any update on it?

**Comment by sansyrox** [comment]
Alright, closing it. Will re-open it if it can be reproduced
