### ISSUE TITLE
integrate uv in the ci pipelines and the docs

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#1020]
integrate uv in the ci pipelines and the docs. it will make the ci faster and result in better docs

**Comment by dave42w** [comment]
Are you thinking we fully replace poetry with uv or that we support both? The speed that uv is being developed at is amazing.

In the 0.50.x series there is now support in uv for some things that are really helpful for us

1. uv tree --outdated eg
```
 robyn v0.64.0
├── inquirerpy v0.3.4
│   ├── pfzy v0.3.4
│   └── prompt-toolkit v3.0.48
│       └── wcwidth v0.2.13
├── multiprocess v0.70.14 (latest: v0.70.17)
│   └── dill v0.3.9
├── nestd v0.3.1 (latest: v0.3.2)
├── orjson v3.9.15 (latest: v3.10.11)
├── rustimport v1.3.4 (latest: v1.5.1)
│   └── toml v0.10.2
├── uvloop v0.19.0 (latest: v0.21.0)
├── watchdog v4.0.1 (latest: v6.0.0)
└── jinja2 v3.0.1 (extra: templating) (latest: v3.1.4)
    └── markupsafe v3.0.2
```
2. An experimental build system that supportd maturin see https://docs.astral.sh/uv/concepts/projects/#packaged-applications

Given the simpler support for multiple python versions maybe we should do this before supporting python 3.13?

**Comment by dave42w** [comment]
Also it seems sensible to use uv "native" options like `uv add jinja2" instead of the pip interface eg `uv pip install jinja2`

**Comment by dave42w** [comment]
This is my current mode of operation with uv

```
git clone git@github.com:dave42w/Robyn.git
mv Robyn my-new-branch
cd my-new-branch
uv venv
uv python pin 3.12
uv add pre-commit poetry maturin pip pytest patchelf
uv run poetry install --with dev --with test
uv run pre-commit install
uv run maturin develop
uv run test_server
```
in separate terminal
```
uv run pytest
```

Note that I add pip and patchelf and pytest as otherwise I can't build and get lots of test warnings
