### ISSUE TITLE
Python 3.8 is officially now unsupported

### ISSUE THREAD

**Issue by dave42w** [sparckles/Robyn#1042]
### Bug Description

See https://www.python.org/downloads/release/python-380/
From Python downloads
```
3.8 end of life, last release was 3.8.20 
First Released 2019-10-14 
End of Support 2024-10-07 
Release Schedule PEP 569
```

I would like to suggest

First, the next release of Robyn drops Python 3.8 we should not support versions of python that are not supported by the psf.

Second, instead of dropping one release a year and going to another version where with source code only security fixes, we should jump forward a bit. Note

-  Python 3.10 has been without bug fixes for well over a year and will have source code only security fixes for 11 more months. It was released 1 day after Robyn 0.7.0 - which is on page 12 of the Robyn releases on github).
- Python 3.11 the last bugfix release was 11 months ago. It was released when Robyn was at version 0.18.1 - somehow Robyn released 0.18.1 before 0.18.0 ;-)
- Python 3.12 will have bug fix releases for another 6 months.

I note that there have been a lot of improvements in Python including speed, typing, and match statement since 3.8

I wonder how many live sites are running on old versions of Python and if any of them are expecting to update to new versions of Robyn without significant work.

### Your operating system

Linux

### Your Python version (`python --version`)

Other (specify below)

### Your Robyn version

main branch

### Additional Info

Python 3.13 by preference Python 3.12 by necessity for Robyn

**Comment by sansyrox** [comment]
@dave42w , you are correct here. Happy to drop support for 3.8. But we will need some work for 3.13 .
