### ISSUE TITLE
BUG: test_web_socket_raw_benchmark(session) fails nox on Windows 3.9

### ISSUE THREAD

**Issue by dave42w** [sparckles/Robyn#1064]
### Bug Description

So this fails ci on nox 

```
@pytest.mark.benchmark
def test_web_socket_raw_benchmark(session):
...
    # this will close the connection
    ws.send("test")
    assert ws.recv() == "Connection closed"
```

This is working through this in base_routes.py
```
@websocket.on("message")
async def message(ws: WebSocketConnector, msg: str, global_dependencies) -> str:
    global websocket_state
    websocket_id = ws.id
    state = websocket_state[websocket_id]
    resp = ""
    if state == 0:
        resp = "Whaaat??"
        await ws.async_broadcast("This is a broadcast message")
        ws.sync_send_to(websocket_id, "This is a message to self")
    elif state == 1:
        resp = "Whooo??"
    elif state == 2:
        await ws.async_broadcast(ws.query_params.get("one"))
        ws.sync_send_to(websocket_id, ws.query_params.get("two"))
        resp = "*chika* *chika* Slim Shady."
    elif state == 3:
        ws.close()

    websocket_state[websocket_id] = (state + 1) % 4
    return resp
```

For some reason on Python 3.9, windows there is a problem with this. But are we actually testing what we should be testing? 
I'm not sure why we don't simply test the close message.

If nothing else the comment is very confusing (it's not obvious why sending a "test" message would cause the web socket to close).

```
@pytest.mark.benchmark
def test_web_socket_raw_benchmark(session):
...
    # this will close the connection
    assert ws.close() == "Connection closed"
```
At least we could make this change and see of nox then passes on python 3.9 windows.

### Steps to Reproduce

Submit any PR, look at the NOX results

### Your operating system

Linux

### Your Python version (`python --version`)

3.12

### Your Robyn version

main branch

**Comment by sansyrox** [comment]
Closing this. As it has been temporarily fixed.
