### ISSUE TITLE
Chinese Mainland cannot access documents

### ISSUE THREAD

**Issue by chiangbar** [sparckles/Robyn#1074]
Unfortunately, the development documents cannot be accessed in Chinese Mainland: https://robyn.tech/documentation

**Comment by sansyrox** [comment]
Hey @chiangbar 👋 

It is hosted on vercel. Does chinese mainland have any restriction on vercel?

**Comment by chiangbar** [comment]
Hahaha, you must use VPN

**Comment by sansyrox** [comment]
Alright, closing this.
