### ISSUE TITLE
ci failing because of rust clippy

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#1080]
### Bug Description

fix rust clippy

### Your operating system

None

### Your Python version (`python --version`)

None

### Your Robyn version

None

**Comment by dave42w** [comment]
Yes please, this will be great. My github notifications are overwhelmed with these PR failures.

Hopefully, this will also tackle the Python 3.13 issue as well as the message indicates that this issue is with the old pyo3

```
note: the attribute macro `pymethods` may come from an old version of the `pyo3_macros` crate, try updating your dependency with `cargo update -p pyo3_macros`
```
