### ISSUE TITLE
Questions about query_params

### ISSUE THREAD

**Issue by WaterEmissary** [sparckles/Robyn#1084]
query_params (QueryParams): The query parameters of the request. e.g. /user?id=123 -> {"id": [ "123" ]}

Why /user? Id = 123 - > {"id": [ "123" ]} rather than return {" id ":" 123"}

**Comment by sansyrox** [comment]
Hey @WaterEmissary 👋 

We support multiple query params with the same name. e.g. /id=1&id=2&id=3 .

**Comment by WaterEmissary** [comment]
Oh, that's it. I see
