### ISSUE TITLE
[Feature Request] Enhance CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Susmita-Dey** [sparckles/Robyn#169]
**Current Behavior**

**Desired Behavior**

I want to enhance the contributing file to make it look beautiful and also add some more lines. Kindly assign this issue to me.
---
**Screenshots / Mockups**

**Alternatives**

---

**Comment by sansyrox** [comment]
@Susmita-Dey , what do you have in mind regarding the improvement?

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey , what do you have in mind regarding the improvement?

I want to enhance it with emojis and add a line like "Congratulations on your first contribution to this repository".

**Comment by sansyrox** [comment]
> "Congratulations on your first contribution to this repository".

@Susmita-Dey , would that involve using some sort of github action?

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey , would that involve using some sort of github action?

No, the emojis would be added manually.

**Comment by sansyrox** [comment]
Perfect! @Susmita-Dey , you can go ahead! :D

**Comment by Susmita-Dey** [comment]
> Perfect! @Susmita-Dey , you can go ahead! :D

Thanks. Kindly assign this to me as there's no one assigned showing in the assignees section.

**Comment by sansyrox** [comment]
@Susmita-Dey , done!

**Comment by sansyrox** [comment]
This is stale. No longer needed
