### ISSUE TITLE
[Feature Request] [Experiment] See if incremental spawning of threads helps reduce the CPU usage

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#213]
**Current Behavior**
Add a way to see if the incremental increase reduces CPU usage.

**Desired Behavior**

Experiment. 

---
**Screenshots / Mockups**

**Alternatives**

---

**Comment by Anirudh-2628** [comment]
Hey i am new to this, can anybody help out how should I start contributing to this?

**Comment by sansyrox** [comment]
Hi @Anirudh-2628 ,

I am happy to help :D

What are your queries?

**Comment by sansyrox** [comment]
stale
