### ISSUE TITLE
[Feature Request] Add a way to have default authentication or authorisation

### ISSUE THREAD

**Issue by sansyrox** [sparckles/robyn#245]
**Current Behavior**
 
Currently, Robyn does not support a default authentication and authorization feature.

**Desired Behavior**

I would like to add a default authorization feature that would still be overridable by the developer if need be.

A good place to understand the `authorization` concept is: https://www.neoteroi.dev/blacksheep/authorization/ 

A high level plan of implementation could be:

- Add a default `authentication` function ( need to research on the choice of the default authentication library)
- Add a default middleware for `authorization`, either through `middleware-chaining`(if implemeted) or default callbacks. 
- Add a default decorator for `per route authorization`

**Comment by sansyrox** [comment]
Hey @carlosm27 ,

You can take up this issue 😊

Let me know if you require any assistance from my end 🖖

**Comment by Oluwaseun241** [comment]
@carlosm27 are you still on it??
