### ISSUE TITLE
[Feature Request] Add openapi integration

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#247]
**Current Behavior**

Robyn doesn't generate [OpenAPI](https://swagger.io/specification/) documentations by default. OpenAPI integration is a highly demanded feature and I am super keen on supporting it.

**Desired Behavior**

A few good links to have a look at are:

- https://github.com/marshmallow-code/apispec
- https://github.com/tiangolo/fastapi/blob/bcabbf8b37db3fbc020560e94ad2f90e64d1510a/fastapi/openapi/docs.py#L1

A high level way of implementing the feature would require:
- Adding a `documentation` route(r)
- Make it configurable
- Make it adhere to the passed params `--dev/--prod`
- Create a class that has OpenAPI pre-requisites (pre-populating-html strings, reponse_parser, etc.)
- Pass it to the threadpool.

**Comment by sansyrox** [comment]
https://github.com/tiangolo/fastapi/blob/bcabbf8b37db3fbc020560e94ad2f90e64d1510a/fastapi/openapi/docs.py#L1

**Comment by Mr-Sunglasses** [comment]
![image](https://github.com/sparckles/robyn/assets/81439109/88107639-0127-4004-968e-e1635a91d683)

**Comment by patrickelectric** [comment]
Is there a PR or a draft open for it ?
