### ISSUE TITLE
[Feature Request] [Long Stretch - Experimentation] - Research on how/if having a custom compiler will help

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#281]
**Current Behavior**

I just read that `youtube-dl` has a custom compiler for JS. Maybe consider having a custom compiler for something in Robyn? Have a CLI tool that pre-compiles before running the app?

**Desired Behavior**

This suggestion could either be incredibly stupid or smart. Either way, worth checking it out.

---
**Screenshots / Mockups**

**Alternatives**

---

**Comment by kliwongan** [comment]
https://news.ycombinator.com/item?id=32793061 might help put it into perspective

**Comment by sansyrox** [comment]
Not doing this for now. Maybe later
