### ISSUE TITLE
[Feature Request] [Long Stretch - Experimentation] - Try writing and compiling in a python docstring

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#284]
**Current Behavior**

Rust cannot be written in Python code.

**Desired Behavior**

Try writing rust code in Python docstrings.

Either this will one of the stupidest or the smartest things. I am not sure. But I sure it will be fun to implement.
---
**Screenshots / Mockups**

**Alternatives**

---

**Comment by KaviiSuri** [comment]
Hey, I'm knew to rust but I'd love to pick this up if it's okay

**Comment by sansyrox** [comment]
@KaviiSuri , sure go ahead. But this is an experimental feature and will require some research. I will be happy to collaborate with you if need be :smile:

**Comment by KaviiSuri** [comment]
@sansyrox thanks!

I'd love to hack around on this, do you have any ideas where I should get started?

 I'll do a little research too and then we can talk on discord maybe?

**Comment by sansyrox** [comment]
Perfect @KaviiSuri ✨ 

I would approach it like this:

1. Extract the docstring from the function.
2. Try accepting python in docstring. Then replace it with rust.
3. See if you can compile rust generated from the docstring.
4. We can see how we will handle arguments after that.

**Comment by sansyrox** [comment]
https://github.com/mityax/rustimport

Something like this could be helpful.

**Comment by sansyrox** [comment]
@KaviiSuri , I had the same idea in mind.

I was looking at this library https://github.com/mityax/rustimport

Lmk what you think of it 😊

**Comment by sansyrox** [comment]
we already have rust now. No need of rust in docstrings
