### ISSUE TITLE
[Feature Request] Convert the returned dictionaries directly to json?

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#393]
**Current Behavior**

Writing `jsonify` to return the json forms of dictionary is cumbersome.

**Desired Behavior**
 Let's return the json response directly when someone is returning a dictionary?

---

**Screenshots / Mockups**

**Alternatives**

---

**Comment by AntoineRR** [comment]
Currently, returning a dictionary is supported but it creates the response from it:
```
@app.get("/async/dict")
async def async_dict_get():
    return {
        "status_code": 200,
        "body": "async dict get",
        "type": "text",
        "headers": {"async": "dict"},
    }
```

This will not make the route return a json but a simple plain text body. Do you think we should change this behavior and rely on the `Response` class when there is a need to specify the headers of the response for example? I think it makes sense but this will be a breaking change.

**Comment by sansyrox** [comment]
Can do something similar to this https://docs.rs/axum/latest/axum/#responses

**Comment by sansyrox** [comment]
done
