### ISSUE TITLE
[Feature Request] Use Poetry for packaging

### ISSUE THREAD

**Issue by XChikuX** [sparckles/robyn#398]
**Current Behavior**

Pip and conda are very tedious to maintain, and should be avoided at all costs. Maintenance of package dependencies is an NP complete problem. 

**Desired Behavior**

Poetry uses best practices to balance updating packages and keeping them stable for a specific project. 

```
python3 -m venv <directory>
pip install poetry
```

A combination of virtual environment and poetry is something I would highly recommend using. Especially in the main readme of the project as well. 

---

**Screenshots / Mockups**

**Alternatives**

---

**Comment by sansyrox** [comment]
Hi @XChikuX ,

Thanks for raising this issue. Back when Robyn was started, there wasn't much documentation on using `maturin` build system with poetry. 

I found this sample https://github.com/kfields/hello-maturin/blob/main/pyproject.toml, but I still need more documentation. I would love to implement this feature, though.

**Comment by XChikuX** [comment]
@sansyrox Poetry uses pip underneath. It's just a wrapper to keep things updated.

Won't this suffice?

```
02:24:21 (.env) root@Chiku-ROG backend ±|main|→ poetry add maturin
Using version ^0.14.12 for maturin

Updating dependencies
Resolving dependencies... (0.7s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals
```

**Comment by sansyrox** [comment]
@XChikuX , there is not much value in using poetry if are not using `poetry build`, `poetry publish` commands. And for that we need a custom build system as Robyn Is a Rust and Python hybrid app.

It will still be somewhat beneficial but we will have do everything through a poetry shell, which is not the best way.

**Comment by XChikuX** [comment]
Got it!

Thanks for looking into this. I hope we find a way to support it.

**Comment by XChikuX** [comment]
Awesome!! Thank you for the hard work @IdoKendo.

@sansyrox Let's update Readme.md to reflect poetry installs?
