### ISSUE TITLE
Move the docs to docs.robyn.tech

### ISSUE THREAD

**Issue by AntoineRR** [sparckles/Robyn#422]
As stated in #417, we should move the docs to the `docs.robyn.tech` URL.
The netlify bot will have to be modified to deploy previews of the website when the content of the `docs` folder is modified.

**Comment by Oluwaseun241** [comment]
Can i work on this??

**Comment by AntoineRR** [comment]
Hi @Oluwaseun241, if you have an idea how to get started sure, feel free to work on this! @sansyrox should be more familiar than me with the way we serve docs right now if you need some help.

**Comment by Oluwaseun241** [comment]
@sansyrox how do i go about this?

**Comment by sansyrox** [comment]
@Oluwaseun241 , I had a suggestion on this issue. Changing the URL can be done only on my end. However, we were hoping for revamping the entire documentation website.

That way we won't have to worry this move. Would you be interested in working on something of this sort?

**Comment by Oluwaseun241** [comment]
Sure would like to work on it

**Comment by sansyrox** [comment]
@Oluwaseun241 perfect. Are you a part of our discord channel?

**Comment by Oluwaseun241** [comment]
No

**Comment by sansyrox** [comment]
@Oluwaseun241 maybe you can join here https://discord.gg/ANTtVXKT

It will be faster to discuss design there 😊

**Comment by sansyrox** [comment]
This is no longer needed.
