### ISSUE TITLE
Create a dev container for Robyn

### ISSUE THREAD

**Issue by shivaylamba** [sparckles/Robyn#492]
This issue proposes the establishment of a Robyn dev container, which would enable speedy installation of Robyn and all of its dependencies when using GitHub Codespaces or VS Code.

**Comment by shivaylamba** [comment]
We decided to instead create a Github Codespace <> Robyn quickstart template: https://github.com/sparckles/robyn-quickstart-template

**Comment by Mr-Sunglasses** [comment]
> We decided to instead create a Github Codespace <> Robyn quickstart template: https://github.com/sparckles/robyn-quickstart-template

@sansyrox We can close it as it's already completed.

**Comment by sansyrox** [comment]
Yes @Mr-Sunglasses , thank you :D
