### ISSUE TITLE
Robyn CLI - Add ability to scaffold different kinds of projects

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#511]
Issue:

As of now, the Robyn CLI tool has limited scaffolding capabilities and does not support a variety of project types. Developers may need to create applications with different backends such as MongoDB, PostgreSQL, or utilizing an ORM like SQLAlchemy. These different needs necessitate the extension of the Robyn CLI to scaffold these types of projects effectively.

Expected Behavior:

When a user invokes the Robyn CLI to scaffold a new project, they should be able to specify the project type based on the intended backend technology or ORM. The resulting scaffolded project should have the appropriate boilerplate code and dependencies set up for the selected type.

Steps to Reproduce:

Run a Robyn CLI command to scaffold a new project (e.g., `python -m robyn --create`).
Notice the lack of options to specify the project type based on different backend technologies or ORMs.
Suggested Solution:

Extend the Robyn CLI to accept a project type as an argument and scaffold the project accordingly. For instance, we could provide options like --mongo, --postgres, or --sqlalchemy to scaffold a MongoDB, PostgreSQL, or SQLAlchemy project, respectively.

**Comment by Oluwaseun241** [comment]
@sansyrox here we go again 😁

**Comment by Mr-Sunglasses** [comment]
Hey @sansyrox, I'm taking this issue 😄 . For the SQL database, I need to ask whether we can do it this way like `-postgres --orm` to generate a postgres template with sqlalchemy and if `--postgres` for generating without sqlalchemy. We can have the option of `--sqlalchemy` also. And we are using the default std library argparse for taking command line arguments, IMO it is fantastic. Still, we can also shift to [Typer](https://typer.tiangolo.com/), if provide a beautiful CLI interface.

<hr>
ps Adding a bat signal for superfast response 😊😅

<p align="center">
  <img width="250" src="https://cdn.wallpapersafari.com/55/43/RZbjGC.jpg">
</p>

**Comment by TroyFPV48** [comment]
Hi all! I and my team will work on this issue as well and I'm happy to connect with anyone who has previously been assigned to this problem!

**Comment by Mr-Sunglasses** [comment]
hey @TroyFPV48 I'm previously working on this problem, and I'm happy to collaborate 👍🏻

**Comment by sansyrox** [comment]
Hey @TroyFPV48 👋

Are you on our discord??

**Comment by TroyFPV48** [comment]
Hi @sansyrox 
No, I'm not, feel free to invite me!

**Comment by sansyrox** [comment]
Perfect, thanks @TroyFPV48 :D

**Comment by TonySherman** [comment]
@sansyrox - is there any chance, this issue could be opened back up? @TroyFPV48 and some others from CodeDay Labs have some more work towards some scaffolds for different database connections. They did notice the addition of inquirerpy from @Mr-Sunglasses and were making changes to include that library in the CLI.

**Comment by sansyrox** [comment]
@TonySherman sure. Done 😊
