### ISSUE TITLE
Router Level Dependency injection

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#543]
I have this idea where we can inject dependencies based on router levels, and if someone needs more granularity, we can add dependencies per route in a router.

Sub routers will have a set of their dependencies, and will inherit the dependencies from the greater router they're included into. And in case of collisions, the local router dependency will be given the priority.

**Comment by sansyrox** [comment]
I was thinking of a concept of `@router.inject` and `@router.inject_route('/route')` and possibly `@router.inject_get('/route')` and so on for post,put and other methods.

**Comment by sansyrox** [comment]
Traditionally, we have something like the following in our router

```
app = Robyn(__file__)

@app.get("/")
def hello():
    return "world"
    
@app.get("/route")
def route():
     return "route"
```

We can add dependencies in two ways:

```
def dependency():
   pass

def dependency2():
   pass

app.inject_dependency(dependency) # this injects the dependency throughout the router

app.inject_dependency("/route", dependency2) # this will be only avaible in the routes
```

and optionally(up for discussion)

we can have something like the following

```
app.inject_dependency("/route", HTTP.GET, dependency2)
```

When we are trying to access the dependencies, we can access them in the following way

```
dependencies = app.get_injected_dependencies() # should be a dict ideally
```
and the dependencies would be available in the functions as well

```
@app.get("/")
def hello(request, dependency):
    return "world"
    
@app.get("/route")
def route(request, dependency, dependency2):
    return "world"
```


These dependencies will be namespaced to a router. So, e.g. if we have a dependency mapped to a global router, then it can also be accessed via a the subrouter.

**Comment by koryca** [comment]
I would like to take this issue with my teammate Darren and Fernando from Codeday Lab : )

**Comment by sansyrox** [comment]
done
