### ISSUE TITLE
Update link for Robyn Docs in robyn/__main__.py

### ISSUE THREAD

**Issue by shivaylamba** [sparckles/Robyn#560]
### Bug Description

Currently the robyn docs link is broken. It needs to be updated with the current base for Robyn docs which exist over here: https://github.com/sparckles/docs-base

**Comment by shivaylamba** [comment]
Yeah I know, once the docs go live, we can replace it.

**Comment by Mr-Sunglasses** [comment]
> Yeah I know, once the docs go live, we can replace it. Makes sense to replace the broken link with the robyn.tech link for now.

 Done I have Updated the link, Thanks @shivaylamba 😄

**Comment by Mr-Sunglasses** [comment]
@sansyrox I think this issue is fixed, we can close it now.

**Comment by sansyrox** [comment]
@Mr-Sunglasses , yep done!
