### ISSUE TITLE
Few Rust questions

### ISSUE THREAD

**Issue by vitalik** [sparckles/Robyn#561]
Hi

pretty interesting project and approach - looking forward trying this

I am new to Rust and I'm glad to find this project for some learning process

I basically have few questions (sorry if they are too nooby):

1 - [why is RwLock here](https://github.com/sparckles/robyn/blob/c5e4ad33270a20071fb6e3b30ff550bca033ead8/src/routers/http_router.rs#L13)

```Rust
type RouteMap = RwLock<MatchItRouter<FunctionInfo>>;
```
It seems that routes are created (mutated) during startup and later only used for read?

2) [why workers number is an Arc ](https://github.com/sparckles/robyn/blob/c5e4ad33270a20071fb6e3b30ff550bca033ead8/src/server.rs#L103C9-L103C21)

```Rust
let workers = Arc::new(workers);
```
and then cloned a few times to be passed to .workers(num)

Thank you

**Comment by sansyrox** [comment]
Hey @vitalik 👋 

Thank you for the interest 😄 

Here are the answers to your questions 

1. The `RouteMap` is used across multiple threads. See here - https://github.com/sparckles/robyn/blob/c5e4ad33270a20071fb6e3b30ff550bca033ead8/src/server.rs#L190

HTTPRouter is used across multiple threads and so is the RouteMap at every value.

2. I think this is not needed. Thank you for bringing this to our notice 😄 
Would you like to create a PR to fix this?

Do let me know if you require any more information from my end 😄
