### ISSUE TITLE
If i raise a exceptions and Robyn will not handle them

### ISSUE THREAD

**Issue by T-baby** [sparckles/Robyn#570]
### Bug Description

I tried to add a handle_exception as per the documentation, but nothing worked.

### Steps to Reproduce

```python
@app.exception
def handle_exception(error):
    return {"status_code": 500, "body": f"error msg: {error}"}

@app.get("/")
async def hello(request):
    raise BaseException("BaseException")
    return jsonify({"message": "Hello World"})
```

If I send a request to this URL directly, I just get "Internal server error".

### Your operating system

MacOS

### Your Python version (`python --version`)

3.11

### Your Robyn version

latest

**Comment by T-baby** [comment]
How can we handle 404 status when a route is not defined？

**Comment by sansyrox** [comment]
Hey @T-baby 👋 

Thank you for raising an issue. But there is an issue with the code. You should never raise a `BaseException`, as it serves as the base class for all the other exceptions. You should raise an `Exception` or better a specific exception in your code. I hope this helps 😄 

Let me know if you have any more questions 😄

**Comment by T-baby** [comment]
> 

How can we handle 404 status when a route is not defined？

**Comment by sansyrox** [comment]
Hey @T-baby 👋 

Robyn does handle them.

You can use something like this

```python3
from robyn import Response, Robyn, jsonify, Request
from robyn.exceptions import HTTPException # this is a new feature and will be released in https://github.com/sparckles/Robyn/pull/951

# but you can use any other exception here like raise ValueError

app = Robyn(__file__)

@app.exception
def handle_exception(error):
    return {
        "success": False,
    }

@app.get("/")
def home():
    raise HTTPException(404, "Not Found")

if __name__ == "__main__":
    app.start()

```


Feel free to open the issue if you have any more questions.
