### ISSUE TITLE
How can i import the Url from robyn?

### ISSUE THREAD

**Issue by T-baby** [sparckles/Robyn#574]
### Bug Description

I got an exception message if I want to import the Url: "AttributeError: module 'robyn.robyn' has no attribute 'Url'."

### Steps to Reproduce

```python
from robyn.robyn import Url
```

I try to use dir() to see what properties this class has.

```python
dir(robyn.robyn )
```

```python
['FunctionInfo', 'HttpMethod', 'Identity', 'MiddlewareType', 'Request', 'Response', 'Server', 'SocketHeld', '__all__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'get_version']
```

So how do I import or create a new Url object?

### Your operating system

MacOS

### Your Python version (`python --version`)

3.10

### Your Robyn version

latest

**Comment by sansyrox** [comment]
Hey @T-baby 👋 

Why do you want to create a new url object??

**Comment by sansyrox** [comment]
@T-baby , I think you can pass the url directly as a string, no?

**Comment by T-baby** [comment]
If I want to create a Request object and a Response object for testing, and the Request object uses a Url object as the type of the url field, I need to declare a Url object first.

Such as:
```python
request = Request(
    queries={},
    headers={"Content-Type": "application/json"},
    path_params={},
    body="",
    method="GET",
    url=Url(), 
    ip_addr=None,
    identity=None,
)
```
