### ISSUE TITLE
Add tox or other tools to automate and standardize testing

### ISSUE THREAD

**Issue by Mr-Sunglasses** [sparckles/Robyn#576]
##  Problem I Faced 🥺
While working on #558 😅, I faced the challenge that testing all the `integration_tests` requires either running each test individually or relying solely on Github actions, which run after pushing commits. Unfortunately, the latter option can be quite annoying 🙄 due to the considerable time it takes. As a result, I strongly felt the need for a tool like tox 🚀, which would enable me to run all test cases with just one simple command `tox`.

## The Benefits we get after using these tools:- 

- Easily runs all the tests locally.
- checking your package builds and installs correctly under different environments (such as different Python implementations, versions or installation dependencies).
- running your tests in each of the environments with the test tool of choice.
- acting as a frontend to continuous integration servers, greatly reducing boilerplate and merging CI and shell-based testing.
- Overall it enhances the dev experience.
### IMO we can go ahead with these two tools: [tox](https://tox.wiki/en/4.6.4/) or [nox](https://nox.thea.codes/en/stable/)

@sansyrox What do you think about it 😃 .

**Comment by sansyrox** [comment]
@Mr-Sunglasses 👋 

> I faced the challenge that testing all the integration_tests requires either running each test individually or relying solely on Github actions, which run after pushing commits

This is not true. You can just use the command `pytest` to run your tests. Can you please explain your problem a bit more?

**Comment by Mr-Sunglasses** [comment]
> Using `tox`(and `nox`) you can run all the matrix of python versions with 1 command instead of running `pytest` on each version manually. I actually like `tox` quite a bit!

Yeah, @IdoKendo and @sansyrox I mean by 1 command is that, running and testing in different Python versions with one command, I also like `tox`, and I have used it in many of my previous projects.
