### ISSUE TITLE
--version doesn't work

### ISSUE THREAD

**Issue by sansyrox** [sparckles/robyn#583]
### Bug Description

--version doesn't show the correct version.

fix it

### Your operating system

None

### Your Python version (`python --version`)

None

### Your Robyn version

None

**Comment by Oluwaseun241** [comment]
@sansyrox is this related to the lastest release version??

**Comment by TroyFPV48** [comment]
Hi, can you be more specific I think Robyn CLI commands do not have "--version". How do I reproduce it?

**Comment by sansyrox** [comment]
@Oluwaseun241 , yes.

**Comment by sansyrox** [comment]
Hey @TroyFPV48 👋 

Thanks for pointing it out. We need to add a `--version` flag then 😅
