### ISSUE TITLE
Add an option to add routes without decorator

### ISSUE THREAD

**Issue by IdoKendo** [sparckles/robyn#587]
In some cases, users may want to add routes without using the decorator.
In Flask it is supported with [add_url_rule](https://tedboy.github.io/flask/generated/generated/flask.Flask.add_url_rule.html)

We can use the same syntax:
```py
from robyn import Robyn

app = Robyn(__file__)

def hello(request):
    return "Hello, world!"

app.add_url_rule('/', 'hello', hello)

app.start(port=8080)
```

This can be useful in cases where you are initiating the app in a certain part of your program but would like to retroactively add routes.

**Comment by thearyadev** [comment]
decorators can be used with this syntax

```python
app.get("/get_route")(func)
app.post("/post_route")(func2)
...
```

if the goal is to separate the route management from the logic.

**Comment by IdoKendo** [comment]
> decorators can be used with this syntax
> 
> ```python
> app.get("/get_route")(func)
> app.post("/post_route")(func2)
> ...
> ```
> 
> if the goal is to separate the route management from the logic.

This syntax is pretty "hacky" and unintuitive, making the `add_route` method public makes this option look a lot better, imo.
