### ISSUE TITLE
request queries only outputs the last value of a query parameter

### ISSUE THREAD

**Issue by zzl221000** [sparckles/Robyn#588]
### Bug Description

According to [The WHATWG URL Standard ](https://url.spec.whatwg.org/#interface-urlsearchparams) 

[sequence](https://webidl.spec.whatwg.org/#idl-sequence)<[USVString](https://webidl.spec.whatwg.org/#idl-USVString)> [getAll](https://url.spec.whatwg.org/#dom-urlsearchparams-getall)([USVString](https://webidl.spec.whatwg.org/#idl-USVString) name);

Similar methods need to be implemented

### Your operating system

None

### Your Python version (`python --version`)

None

### Your Robyn version

None

**Comment by sansyrox** [comment]
Hey @zzl221000 

Can you please elaborate a bit this request?

**Comment by zzl221000** [comment]
> Can you please elaborate a bit this request?
```python
url = http://example.com/?field1=value1&field1=value2&field2=value3

queries.get("field1") # result is value1
queries.getAll("field1") # result is [ value1, value2 ]
```
The query string is speciﬁcally allowed to use the same key for list parameters.

**Comment by zzl221000** [comment]
@sansyrox 

https://github.com/sparckles/robyn/blob/main/src/types/request.rs
```rust
#[derive(Default, Debug, Clone, FromPyObject)]
pub struct Request {
    pub queries: HashMap<String, String>,
    pub headers: HashMap<String, String>,
    pub method: String,
    pub path_params: HashMap<String, String>,
    #[pyo3(from_py_with = "get_body_from_pyobject")]
    pub body: Vec<u8>,
    pub url: Url,
    pub ip_addr: Option<String>,
    pub identity: Option<Identity>,
}
```
`queries` is not a hashmap structure, it should be a [multimap](https://docs.rs/multimap/latest/multimap/). headers is the same.


https://github.com/sparckles/robyn/blob/main/src/types/response.rs
```rust
#[derive(Debug, Clone, FromPyObject)]
pub struct Response {
    pub status_code: u16,
    pub response_type: String,
    pub headers: HashMap<String, String>,
    #[pyo3(from_py_with = "get_body_from_pyobject")]
    pub body: Vec<u8>,
    pub file_path: Option<String>,
}
```
[RFC 6265](https://www.rfc-editor.org/rfc/rfc6265)
>Origin servers SHOULD NOT fold multiple Set-Cookie header fields into a single header field. The usual mechanism for folding HTTP headers fields (i.e., as defined in [[RFC2616](https://www.rfc-editor.org/rfc/rfc2616)]) might change the semantics of the Set-Cookie header field because the %x2C (",") character is used by Set-Cookie in a way that conflicts with such folding.

The `Set-Cookie` response header may have more than one.

**Comment by sansyrox** [comment]
Thanks for raising this @zzl221000 😄 

All of this makes sense. We will start working on it 😄

**Comment by sansyrox** [comment]
Taking this up

**Comment by Mng-dev-ai** [comment]
Also, queries should be immutable. The last time I checked it in Robyn, they were mutable.

**Comment by Mng-dev-ai** [comment]
The same for request headers

**Comment by sansyrox** [comment]
Hey @Mng-dev-ai 👋 

I am picking this up. This issue will be fixed in the coming week 😄

**Comment by sansyrox** [comment]
Hey @木大酱 @Mng-dev-ai 👋 

This query params are fixed in the current version. The headers will be fixed in the upcoming version 😄
