### ISSUE TITLE
ModuleNotFoundError: No module named 'uvloop'

### ISSUE THREAD

**Issue by DarthStrom** [sparckles/robyn#594]
### Bug Description

When trying to work through the Getting Started example, I get the following error when trying to run the service:

```
Traceback (most recent call last):
  File "/Users/jason/src/python/robyn-app/venv/lib/python3.11/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/jason/src/python/robyn-app/venv/lib/python3.11/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jason/src/python/robyn-app/venv/lib/python3.11/site-packages/robyn/processpool.py", line 162, in spawn_process
    loop = initialize_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jason/src/python/robyn-app/venv/lib/python3.11/site-packages/robyn/processpool.py", line 127, in initialize_event_loop
    import uvloop
ModuleNotFoundError: No module named 'uvloop'
```

### Steps to Reproduce

1. Work through [getting started](https://sparckles.github.io/robyn/#/getting-started)

### Your operating system

MacOS 13.4.1 (intel processor)

### Your Python version (`python --version`)

3.11.3

### Your Robyn version

0.38.0

**Comment by banipreetr** [comment]
I think this can be attributed to:
https://github.com/sparckles/robyn/blob/main/pyproject.toml#L33

instead of 
```
  "uvloop>=0.17.0; sys_platform == 'darwin' and platform_machine == 'aarch_64' and platform_machine == 'x86_64' and platform_machine == 'i686'"
```

shouldn't it be:

```
  "uvloop>=0.17.0; sys_platform == 'darwin' and (platform_machine == 'aarch_64' or platform_machine == 'x86_64' or platform_machine == 'i686'")
``` 

?

**Comment by sansyrox** [comment]
Yes @banipreetr . This is definitely the issue. 

This could be one solution.

A better solution should be the one below as the current one is too specific.

```
"uvloop~=0.17.0; sys_platform != 'win32' and platform_python_implementation == 'CPython'"
```

We can try both as I feel my solution will require us to alter the CI a bit.

**Comment by banipreetr** [comment]
> Yes @banipreetr , and thanks for the triage 😄 . This is definitely the issue.
> 
> This could be one solution.
> 
> A better solution should be the one below as the current one is too specific.
> 
> ```
> "uvloop~=0.17.0; sys_platform != 'win32' and platform_python_implementation == 'CPython'"
> ```
> 
> We can try both as I feel my solution will require us to alter the CI a bit.

Sounds good to me. I've made a Draft PR with my proposed change.
