### ISSUE TITLE
Broke links in Readme

### ISSUE THREAD

**Issue by tushar5526** [sparckles/robyn#597]
### Bug Description

The link to robyn's architecture under `How to contribute` section is broken. https://github.com/sparckles/robyn#%EF%B8%8F-how-to-contribute

### Your operating system

None

### Your Python version (`python --version`)

None

### Your Robyn version

None

**Comment by tushar5526** [comment]
I also found `view-documentation` badge to be broken in README

**Comment by sansyrox** [comment]
Thanks @tushar5526 :smile: 

A PR has been made to fix this !
