### ISSUE TITLE
add_response_header may fail sometimes

### ISSUE THREAD

**Issue by wukan1986** [sparckles/Robyn#605]
### Bug Description

```python
from robyn import Robyn, jsonify

app = Robyn(__file__)


@app.get("/")
async def h(request):
    return jsonify({"chinese": "中文"})


app.add_response_header("content-type", "application/json; charset=UTF-8")
app.start()
```

when refresh chrome, the output display two results:

`{"chinese":"中文"}`
or
`{"chinese":"涓枃"}`

so, I check it in DevTools,  the `Content-Type` change sometimes

`application/json; charset=UTF-8`
or
`text/plain`

### Your operating system

Windows

### Your Python version (`python --version`)

3.8

### Your Robyn version

None

### Additional Info

INFO:robyn.logger:Robyn version: 0.37.0

Python 3.8.3

**Comment by 18o** [comment]
it's still happened in 0.44.1 with python 3.11.6 on MacOS 14 Sonoma

**Comment by sansyrox** [comment]
Hey @18o 👋 

Thank you for reporting. I will have a look again.
