### ISSUE TITLE
Explain how to use static folder

### ISSUE THREAD

**Issue by paroxyste-0** [sparckles/Robyn#607]
Hello,

I'm having trouble loading my files from the 'static' folder in Jinja. Here's my folder:

![image](https://github.com/sparckles/robyn/assets/145021812/e106bf53-f429-4d4b-a809-112080dd7507)

On the browser, all resources return a 404:

![image](https://github.com/sparckles/robyn/assets/145021812/e5525d12-4ba8-4c1d-adad-1f19f60f4d71)

I tried to follow issue #64  #55 , but I couldn't find my answers. Could you please explain how to do it or update the documentation?

Config > Robyn 0.37 / Python 3.11.5

Best regards

**Comment by sansyrox** [comment]
Hey @paroxyste-0 👋 

Do you just want to serve a directory?

**Comment by harryliang** [comment]
Same question: How to serve a directory? No document found.

**Comment by sansyrox** [comment]
@harryliang , just the documentation for serving files and directories?

**Comment by sansyrox** [comment]
Done here - https://robyn.tech/documentation/api_reference/file-uploads
