### ISSUE TITLE
make the releases heading in the new docs website act as anchors

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#610]
They are only text right now. We need to make them behave as links

**Comment by Light13008** [comment]
hello, 
I'm new to this repo, i looked into ur codebase but i couldn't really get where to apply the changes. 
i looked into new_docs file. 
could you provide me a little guidance.

**Comment by sansyrox** [comment]
https://beta.robyn.tech/releases

Hey @Light13008 👋 

We are talking about the release headings here , like this

<img width="643" alt="image" src="https://github.com/sparckles/Robyn/assets/29942790/8cee17da-db4c-4948-9990-454b2745dc50">


We need these links to be clickable.
