### ISSUE TITLE
Enable hot reloading by default

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#62]
I have been using the --dev=true flag a lot more than the prod build.

It makes sense in my opinion to enable the reload mode by default and have the developer disable it while deploying.

**Comment by Kludex** [comment]
We can enable CLI arguments/options via environment variables as well. For instance, `ROBYN_<argument/option>` will enable the correspondent argument/option.

CLI option should take precedence anyway.

**Comment by Kludex** [comment]
Gunicorn uses a single environment variable to define configuration `GUNICORN_CMD_ARGS`, Uvicorn uses `UVICORN_<argument>`. JFYK
