### ISSUE TITLE
Issue running Robyn in Docker

### ISSUE THREAD

**Issue by bwdq** [sparckles/robyn#621]
### Bug Description

GET 127.0.0.1:8080 returns NS_ERROR_NET_RESET in Firefox and net::ERR_EPTY_RESPONSE in Chrome when Robyn is run in a Docker container. 
The docker file is 
[https://github.com/sparckles/robyn/pull/584/files#diff-c6852d80a152ff247c572adfff265315625a79649e44b8c66f37a871ac4a860c](https://github.com/sparckles/robyn/pull/584/files#diff-c6852d80a152ff247c572adfff265315625a79649e44b8c66f37a871ac4a860c)

`docker build -t robyn-test .`
`docker run -d -p 8080:8080 --name robyn-test robyn-test`

![image](https://github.com/sparckles/robyn/assets/113181952/f3f79083-31db-4e10-9929-3e660dd2245c)
![image](https://github.com/sparckles/robyn/assets/113181952/78c86376-b8f1-4a31-aed6-20864e76c56b)

### Steps to Reproduce

1. Docker build
2. Docker run
3. GET in browser

### Your operating system

Windows

### Your Python version (`python --version`)

3.11

### Your Robyn version

Other (specify below)

**Comment by sansyrox** [comment]
You need to use url='0.0.0.0' in app.start



app.start(url='0.0.0.0',8080)

Let me know if that works

**Comment by bwdq** [comment]
It worked with `app.start(url='0.0.0.0',port=8080)`

Thank you, closing this
