### ISSUE TITLE
Community resources link on README not working

### ISSUE THREAD

**Issue by github-education** [sparckles/Robyn#627]
### Bug Description

When a users clicks on the community resources link on the README, they get redirected to a 404 page meaning the link is not working properly. 

### Steps to Reproduce

1. https://github.com/sparckles/Robyn/blob/5b39cd5ca40d92676227b5dd498662d3b6edd2ec/README.md?plain=1#L14C181-L14C187

### Your operating system

None

### Your Python version (`python --version`)

None

### Your Robyn version

None

**Comment by github-education** [comment]
I would love to take this issue and solve it.

**Comment by sansyrox** [comment]
Please go ahead 😄
