### ISSUE TITLE
Typo in README?

### ISSUE THREAD

**Issue by tushar5526** [sparckles/Robyn#632]
https://github.com/sparckles/Robyn#-define-your-api

```python
from Robyn import Robyn

app = Robyn(__file__)

@app.get("/")
async def h(request):
    return "Hello, world!"

app.start(port=8080)
```

I am getting an unresolved reference error for `Robyn`. Shouldn't it be?
```python
from robyn import Robyn
```

**Comment by carlosm27** [comment]
Hey @tushar5526. Thank you for rise this issue. Yes, you're right it should be:
```python
from robyn import Robyn
```

**Comment by sansyrox** [comment]
Thank you @tushar5526 and @carlosm27 😄 😄
