### ISSUE TITLE
--fast flag inspired by sanic framework

### ISSUE THREAD

**Issue by tushar5526** [sparckles/Robyn#636]
Sanic has its own webserver along with support for external webservers. Servers like `uvicorn`, `gunicorn` leave it up to the users to tweak the value of `processes`, `workers` or `threads` to find the best combination which gives the best performance. 

But Sanic's own webserver has a `--fast` flag which automatically optimises these values according to your server. Robyn should support something like it to tweak the values of `processes` and `workers`.

**Comment by sansyrox** [comment]
Hey @tushar5526 👋 

That is a great idea. Thank you. I will have a look 😄

**Comment by sansyrox** [comment]
Hey @mn3711698 👋 

Can you please explain a bit more ? What do you mean by this

> Currently encountering high concurrency issues, please as soon as possible

How are you running Robyn?

**Comment by mn3711698** [comment]
@sansyrox 

i know  just lite english.
my website running Robyn.
Robyn should support something like it to tweak the values of processes and workers ?

**Comment by sansyrox** [comment]
Hey @mn3711698 👋 

It is super easy to do that in Robyn 😄 

Just do `python3 app.py --workers=N --processes=M`

**Comment by sansyrox** [comment]
https://robyn.tech/documentation/api_reference/const_requests#muli-core-scaling

**Comment by sansyrox** [comment]
Also, @mn3711698 , I would love to see your website 😄  You can share it with me on Discord if that is more comfortable.

**Comment by sansyrox** [comment]
Hey @mn3711698 @tushar5526 This has been introduced in v0.60.2
