### ISSUE TITLE
Robyn `--create` template typo.

### ISSUE THREAD

**Issue by Mr-Sunglasses** [sparckles/Robyn#657]
### Bug Description

When We create a new project using `python3 -m robyn --create` it should create the from from this template

```

from robyn import Robyn

app = Robyn(__file__)


@app.get("/")
def index():
    return "Hello World!"


if __name__ == "__main__":
    app.start()
```

But it is creating 

```
from Robyn import Robyn

app = Robyn(__file__)


@app.get("/")
def index():
    return "Hello World!"


if __name__ == "__main__":
    app.start()
```

Ref : [Line](https://github.com/sparckles/Robyn/blob/02460f678684a43a80bdee35461ab5985741bced/robyn/__main__.py#L36C5-L36C5) Which is giving an Import error.

### Steps to Reproduce

python3 -m robyn --create

cd app/

python3 main.py

```
Traceback (most recent call last):
  File "/Users/kanishkpachauri/Desktop/oss/robyn/app1/app.py", line 2, in <module>
    from Robyn import Robyn
ModuleNotFoundError: No module named 'Robyn'
```

### Your operating system

MacOS

### Your Python version (`python --version`)

3.11

### Your Robyn version

main branch

**Comment by Mr-Sunglasses** [comment]
Hey, @sansyrox 👋🏻  While going through the `git blame` of the file `__main__.py` I noticed that this [PR ](https://github.com/sparckles/Robyn/commit/97b87691e894229129890eae8c4743aae0a6d769) breaks a lot of things inside the repo as it had just find and replace `robyn` to `Robyn` so it caused a lot of things to break. I'm finding if anymore things should have braked with this PR and fixing it 😄 .

**Comment by sansyrox** [comment]
Thank you @Mr-Sunglasses 😄 ✨
