### ISSUE TITLE
move create robyn app into a separate repo

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#659]
### Bug Description

It is getting hard to test the create flag. We need to create a new repo for the same.

### Your operating system

None

### Your Python version (`python --version`)

None

### Your Robyn version

None

**Comment by Mr-Sunglasses** [comment]
Hey @sansyrox Do you mean a separate `cli` directory inside the `robyn` package directory?

ie: 

```
robyn/
├── __init__.py
├── __main__.py
├── cli
│   ├── __init__.py
│   ├── cli_files_here_.py
├── argument_parser.py
├── authentication.py
├── env_populator.py
├── events.py
├── logger.py
├── processpool.py
├── py.typed
├── reloader.py
├── responses.py
├── robyn.cpython-311-darwin.so
├── robyn.pyi
├── router.py
├── status_codes.py
├── templating.py
├── types.py
└── ws.py
```

**Comment by sansyrox** [comment]
Hey @Mr-Sunglasses . Neither.

In a separate GitHub repo, which we can clone.

**Comment by Mr-Sunglasses** [comment]
> Hey @Mr-Sunglasses . Neither.
> 
> In a separate GitHub repo, which we can clone.

Are we doing this in the next release or anytime soon because I'm solving #635 which will affect by this.

**Comment by itsayopapi** [comment]
@sansyrox Can I still attempt to do this issue?

**Comment by sansyrox** [comment]
@Mr-Sunglasses @itsayopapi  , this is supposed to be done soon but it is blocked on a PR atm. This one - https://github.com/sparckles/Robyn/pull/584

**Comment by itsayopapi** [comment]
@Mr-Sunglasses can we collaborate?

**Comment by Mr-Sunglasses** [comment]
> @Mr-Sunglasses can we collaborate?

Hey Sure I'm open for help and collaboration, If you need any help in any issue just ping me up 🤠

**Comment by itsayopapi** [comment]
@Mr-Sunglasses What is your Discord?

**Comment by Mr-Sunglasses** [comment]
> @Mr-Sunglasses What is your Discord?
> 
@itskanishkp is my discord and I'm active on Robyn server

**Comment by itsayopapi** [comment]
@Mr-Sunglasses I cant find you on discord...try to search for me


@the.african_gorilla

**Comment by itsayopapi** [comment]
@Mr-Sunglasses Done

**Comment by sansyrox** [comment]
I don't think we need to address this issue. `create-robyn-app` should be here only.
