### ISSUE TITLE
We need the expediency of immaturity

### ISSUE THREAD

**Issue by goSeeFuture** [sparckles/Robyn#695]
Robyn is a great project!

The fact that some bugs are hard to fix isn't going to be a big problem that affects usage (e.g. #622), it's the ones that can't be bypassed using Python that really affect usage (e.g. #588).

When it takes a long time to fix bugs, users will quit using Robyn because they can't use their Python experience to solve the problem, so maybe we can expose the relevant data to Python users while preserving the original design of the interfaces, so that users can continue to use them, and the development team has enough time to solve the problems, which is a good stopgap for both sides, I think this is a good expedient for both sides.

I'm developing a project using Robyn and am stuck at #588, really wish there was a way I could continue, I love Robyn!

**Comment by sansyrox** [comment]
Hello @goSeeFuture 👋 

Thank you so much for your kind words and support for Robyn! We completely understand your concerns regarding issue #588 and the impact it has on your project development. Rest assured, we're treating this issue as a high priority. However, it's important to note that, I don't work full-time on OSS yet 😉 . This can sometimes lead to longer than ideal issue triage and resolution times.

We truly value the feedback and insights from our community, and it's contributions from users like you that help us improve and evolve. If you're inclined and able, we would absolutely love to see any contributions you might have to help address this issue or enhance Robyn in other ways. Community involvement is vital for open-source projects, and every bit of help or insight can make a significant difference.

In the meantime, we'll keep working diligently to resolve this as quickly as possible. Your understanding and continued support are greatly appreciated!

Best regards,
Sanskar

**Comment by sansyrox** [comment]
I am closing this issue, and will be following up on #588 directly. Feel free to reopen if you have any more questions/suggestions.
