### ISSUE TITLE
https://robyn.tech/ can not be open

### ISSUE THREAD

**Issue by shaohaiyang** [sparckles/Robyn#734]
### Bug Description

ERR_CONNECTION_TIMED_OUT

### Your operating system

MacOS

### Your Python version (`python --version`)

3.11

### Your Robyn version

main branch

**Comment by sansyrox** [comment]
Hey @shaohaiyang 👋 

The website is working fine for me. Can you please check one more time?

**Comment by shaohaiyang** [comment]
Surprise ， it can be opened today.

**Comment by shaohaiyang** [comment]
Surprise
