### ISSUE TITLE
Pydantic v2 breaking Robyn 

### ISSUE THREAD

**Issue by shaohaiyang** [sparckles/Robyn#735]
### Bug Description

when use :

`python3 -m robyn --create`

the demo code running report: 

> 
>   File "/app/app.py", line 27, in h
>     return user.json(indent=2)
>            ^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 1011, in json
>     raise TypeError('`dumps_kwargs` keyword arguments are no longer supported.')
>  TypeError: `dumps_kwargs` keyword arguments are no longer supported.
> 

### Your operating system

Linux

### Your Python version (`python --version`)

3.11

### Your Robyn version

latest

### Additional Info

Should be specify a pydantic version in the requirement.txt to work
`pydantic==1.10.11`

**Comment by sansyrox** [comment]
Hey @shaohaiyang 👋

Thank you for reporting the issue. This looks more like a pydantic issue. 

Can you please paste your code here?

**Comment by shaohaiyang** [comment]
The code just generated using robyn default create.
```

from robyn import Robyn
from prisma import Prisma
from prisma.models import User

app = Robyn(__file__)
prisma = Prisma(auto_register=True)


@app.startup_handler
async def startup_handler() -> None:
    await prisma.connect()


@app.shutdown_handler
async def shutdown_handler() -> None:
    if prisma.is_connected():
        await prisma.disconnect()


@app.get("/")
async def h():
    user = await User.prisma().create(
        data={
            "name": "Robert",
        },
    )
    return user.json(indent=2)


if __name__ == "__main__":
    app.start(host="0.0.0.0", port=8080)

```

**Comment by sansyrox** [comment]
@shaohaiyang , were you able to fix this issue?

**Comment by panla** [comment]
Prisma is dead
