### ISSUE TITLE
docker file - copy the files before pip install

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#745]
### Bug Description

docker file - copy the files before pip install

docker build will fail otherwise

### Your operating system

None

### Your Python version (`python --version`)

None

### Your Robyn version

None

**Comment by 13Mai13** [comment]
Which dockerfile are you referring to? Wasn't this fixed in https://github.com/sparckles/Robyn/pull/750

**Comment by sansyrox** [comment]
You are correct, @13Mai13 . Thank you for the triage 😄
