### ISSUE TITLE
SQLAlchemy template has typo in import

### ISSUE THREAD

**Issue by isaacharrisholt** [sparckles/Robyn#755]
### Bug Description

The SQLAlchemy template has a typo in the `models.py` file:

```py
from sqlalchem.orm import Boolean, Column, Integer, String
```

`sqlalchem` should be `sqlalchemy` with a `y`.

### Steps to Reproduce

1. `robyn --create`
2. Choose SQLAlchemy template

### Your operating system

Linux

### Your Python version (`python --version`)

3.11

### Your Robyn version

latest

### Additional Info

Robyn version 0.52.0

**Comment by sansyrox** [comment]
Thank you @isaacharrisholt , I will fix it ✨

**Comment by sansyrox** [comment]
@isaacharrisholt , apologies for the delay. But this has been fixed in the latest Robyn release.
