### ISSUE TITLE
query_params.get("param_name") requires a default value

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#763]
### Bug Description

query_params.get("param_name") requires a default value

this default value should be optional and not manadataed

### Your operating system

None

### Your Python version (`python --version`)

None

### Your Robyn version

None

**Comment by StandinKP** [comment]
Seems valid. I would like to take this up if noone is working on this

**Comment by StandinKP** [comment]
https://github.com/sparckles/Robyn/blob/7309086ac1b20c088e87e8028c23abc3f31f3da7/src/types/multimap.rs#L28

The query params are Optional and return None as well
