### ISSUE TITLE
document the redirection issue

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#800]
document a way for redirects in the code

**Comment by sarfarazsiddiquii** [comment]
hey @sansyrox i would like to contribute, can you please elaborate the issue?

**Comment by VishnuSanal** [comment]
hi, can you elaborate on what the "redirection issue" is? I searched up for history in issues, but did not find anything. 🤔

**Comment by sansyrox** [comment]
Hey @VishnuSanal , this issue requires a way to document how to redirect to a different link, I.e. using the internal redirect or using a 301 response code
