### ISSUE TITLE
On Mac, ctrl+c to quit the app raises alert

### ISSUE THREAD

**Issue by virajkanwade** [sparckles/Robyn#817]
### Bug Description

Python quit unexpectedly.
Click Reopen to open the application again. Click Report to see more detailed information and send a report to Apple.

### Steps to Reproduce

Run the app with `python app.py` or `python -m robyn app.py`
When the app is running press ctrl + c

### Your operating system

MacOS

### Your Python version (`python --version`)

3.12

### Your Robyn version

latest

**Comment by sansyrox** [comment]
hey @virajkanwade ,

Thanks for opening the issue 😄  Just to clarify - you mean `ctrl +c` , right?

**Comment by virajkanwade** [comment]
> Thanks for opening the issue 😄 Just to clarify - you mean `ctrl +c` , right?

Yes, ctrl +c 😆

**Comment by sansyrox** [comment]
I am unable to replicate this. What is your MacOS version @virajkanwade ?

**Comment by virajkanwade** [comment]
@sansyrox 
Sonoma 14.5
Python 3.12
Macbook Pro M2 Max
iTerm 3.4.23

Let me know if you want me to try something.

**Comment by sansyrox** [comment]
@virajkanwade , I am unable to replicate this issue. Could you try one more time? Or maybe if possible share a video?

**Comment by virajkanwade** [comment]
@sansyrox just did a quick test.

<img width="1720" alt="Screenshot 2024-06-01 at 8 51 58 PM" src="https://github.com/sparckles/Robyn/assets/316111/b2ae42b0-20a1-4742-9037-b94684fb924d">

**Comment by virajkanwade** [comment]
@sansyrox I think I found something,

<img width="1143" alt="Screenshot 2024-06-01 at 9 17 24 PM" src="https://github.com/sparckles/Robyn/assets/316111/dccef28a-a564-4a78-a637-a071562a7fcf">


<img width="1151" alt="Screenshot 2024-06-01 at 9 17 38 PM" src="https://github.com/sparckles/Robyn/assets/316111/d4d09124-26ef-4fe3-899f-b34e0b6188c9">

**Comment by virajkanwade** [comment]
`def init_processpool`

`if sys.platform.startswith("win32") or processes == 1:`
calls spawn_process directly.

I think that is the issue in my case.

**Comment by sansyrox** [comment]
@virajkanwade , thanks for diving in. But this is core feature of Robyn 😅 Shouldn't be the reason for a bug. However. I can have a deeper look. Once I upgrade my mac. i.e. within a few days.
