### ISSUE TITLE
Trailing slashes leads to 404

### ISSUE THREAD

**Issue by VishnuSanal** [sparckles/Robyn#818]
### Bug Description

say, I have a route:

```
@app.get("/sync/str/")
def sync_str_get():
    return "sync str get"
```

now, when I do `curl http://localhost:8080/sync/str/`, everything works fine, but if I do a `curl http://localhost:8080/sync/str`, I get a "Not found".

this is the same case if it is vice versa too (slash not being present in the route & slash being present in the URL).

edit: I tried the same thing with flask, and that worked fine.

### Your operating system

Linux

### Your Python version (`python --version`)

3.12

### Your Robyn version

main branch

### Additional Info

ofc, I would like to work on this issue, and I have been debugging it, that led me to `const_router.Router#get_route`.

```
fn get_route(&self, route_method: &HttpMethod, route: &str) -> Option<Response> {
        let table = self.routes.get(route_method)?;
        let route_map = table.read().ok()?;

        match route_map.at(route) {
            Ok(res) => Some(res.value.clone()),
            Err(_) => None,
        }
    }
```

I presume I should add/remove a trailing slash here after checks. @sansyrox please CMIIW. :)

edit: or, we can add both the routes (with & without the slash) in `Server#add_route`, since doing the above approach would introduce an overhead on every request, but this approach only once. what say?

**Comment by sansyrox** [comment]
What I would suggest is to append a `/` to the URL without the `/` and then add it. It will make things a lot simpler

**Comment by VishnuSanal** [comment]
> What I would suggest is to append a `/` to the URL without the `/` and then add it. It will make things a lot simpler

Alright. You meant adding both of them, right?
