### ISSUE TITLE
Error in Crime Data Endpoints Documentation Code

### ISSUE THREAD

**Issue by Amaljyothi44** [sparckles/Robyn#835]
### Bug Description

There is an issue with the get_crimes endpoint in the crime data documentation. The code provided is throwing a TypeError when attempting to retrieve query parameters.
```
@app.get("/crimes")
async def get_crimes(request):
    with SessionLocal() as db:
        skip = request.query_params.get("skip", 0)
        limit = request.query_params.get("limit", 100)
        crimes = crud.get_crimes(db, skip=skip, limit=limit)
    return crimes

**Error:**
skip = request.query_params.get("skip", 0)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'default': 'int' object cannot be converted to 'PyString'
```

### Your operating system

None

### Your Python version (`python --version`)

Python 3.11.3

### Your Robyn version

robyn==0.54.5

### Additional Info

**Corrected Code:**
```
@app.get("/crimes")
async def get_crimes(request):
    with SessionLocal() as db:  # Use SessionLocal here
        skip = request.query_params.get("skip", "0") 
        limit = request.query_params.get("limit", "100")
        skip = int(skip)
        limit = int(limit)
        crimes = crud.get_crimes(db, skip=skip, limit=limit)
    return crimes
```    
@sansyrox please CMIIW

**Comment by sansyrox** [comment]
Hey @Amaljyothi44 👋 

Thanks for raising the issue. Could you confirm your robyn version?

**Comment by Amaljyothi44** [comment]
@sansyrox I have updated the version

**Comment by sansyrox** [comment]
Hey @Amaljyothi44 👋 

One suggestion - please format code snippets using backticks(\`) . But apart from that yes, this is definitely an issue. We could fix it like your suggestion, but maybe we can add a `cast_to` in the request.query_params, which takes a python function callable and tries to cast it to data type.
( https://github.com/sparckles/Robyn/issues/836 )

e.g.

```
@app.get("/crimes")
async def get_crimes(request):
    with SessionLocal() as db:  # Use SessionLocal here
        skip = request.query_params.get("skip",cast_to=int, default=0) 
        limit = request.query_params.get("limit", cast_to=int, default=100)
        skip = int(skip)
        limit = int(limit)
        crimes = crud.get_crimes(db, skip=skip, limit=limit)
    return crimes
```

What do you think of this approach?

**Comment by Amaljyothi44** [comment]
Hi @sansyrox  👋

Thanks for the suggestion! The `cast_to` argument isn't supported in `request.query_params.get`, which is causing an error

```
skip = request.query_params.get("skip",cast_to=int, default=0)        
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        
 TypeError: QueryParams.get() got an unexpected keyword argument 'cast_to'
 
 ````

**Comment by sansyrox** [comment]
Hey @Amaljyothi44 , 

The suggestion is to implement it 😄

**Comment by Amaljyothi44** [comment]
@sansyrox ohhh, sorry 😅,

I agree that using `cast_to` in `request.query_params` is a more efficient and cleaner approach.

**Comment by sansyrox** [comment]
@Amaljyothi44 , would you like to take that up?

**Comment by Amaljyothi44** [comment]
@sansyrox Sure, I'm working on it.

**Comment by Amaljyothi44** [comment]
Hey @sansyrox 👋,

Sorry, I think no need for cast_to argument, changing the data type of the default value will fix the bug more effectively.
