### ISSUE TITLE
suggestion: MAKEFILE

### ISSUE THREAD

**Issue by VishnuSanal** [sparckles/Robyn#839]
how about having a MAKEFILE? for tasks like install, build, clean, etc.

**Comment by sansyrox** [comment]
Hey @VishnuSanal 👋 

I am not a big fan of makefiles as I don't use them myself in development. Instead of that, I use precommit-ci, which pushes changes automatically to the PR. Reducing my time to first commit.

**Comment by sansyrox** [comment]
Closing this. Feel free to reopen if you have any more questions or suggestions regarding the same 😄

**Comment by VishnuSanal** [comment]
> I am not a big fan of makefiles as I don't use them myself in development. Instead of that, I use precommit-ci(https://pre-commit.ci/) , which pushes changes automatically to the PR. Reducing my time to first commit.

@sansyrox I didn't quite get you. I am takling about maing it easier for devs to do simple tasks like build, test, clean, run etc. can this be done with pre-commit? enlighten me! :)

```
dist: server.py client.py
	pyinstaller --clean -y --onefile --add-data="secret-key.json:." --add-data="add_new_icon.png:." --add-data="logo.png:." --add-data="delete_icon.png:." server.py
	pyinstaller --clean -y --onefile --add-data="secret-key.json:." --add-data="logo.png:." client.py

run: client.py server.py
	python3 client.py & disown
	python3 server.py & disown

execute: dist/client dist/server
	./dist/client & disown
	./dist/server & disown

clean:
	rm -f *.spec
	rm -rf build/
	rm -rf dist/
```

this is a makefile from one of my projects, just wrote it for convenience so that I don't have to remember/type in the commands everytime. 🙈
