### ISSUE TITLE
robyn How to set the values of headers, cookie or token. request.headers.set() and response.headers.set() are ineffective.

### ISSUE THREAD

**Issue by xiaojin20** [sparckles/Robyn#851]
这句话的意思是：如何设置标头的值，Cookie 或令牌。request.headers.set() 和 response.headers.set() 是无效的。

How to set the values of headers, cookie or token. request.headers.set() and response.headers.set() are ineffective.

**Comment by xiaojin20** [comment]
headers = {"set-cookie": "image:jpeg"}
        up="files"
        return Response(description=up, headers=headers, status_code=200)

**Comment by sansyrox** [comment]
Hey @xiaojin20 ,



> headers = {"set-cookie": "image:jpeg"}
> up="files"
> return Response(description=up, headers=headers, status_code=200)


Does the above doesn't work?

**Comment by xiaojin20** [comment]
The above is okay, but it's too complicated. Is there a simpler implementation? For example: Response.headers.set("set_cookie","token1=abcd")
上述内容是可以的，但太复杂了。是否有更简单的实现方式？例如：Response.headers.set("set_cookie","token1=abcd")

**Comment by sansyrox** [comment]
Hey @xiaojin20 , I agree with this fact. We need to expose a better interface. Keeping this issue open till we fix it :D

**Comment by sansyrox** [comment]
@xiaojin20 , https://github.com/sparckles/Robyn/issues/854

Tracking the issue here. SHould be implemented in the next few releases.
