### ISSUE TITLE
bug in the dev server reload - should not ask for a different port

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#868]
### Bug Description

INFO:robyn.logger:SERVER IS RUNNING IN VERBOSE/DEBUG MODE. Set --log-level to WARN to run in production mode.
INFO:robyn.logger:Added route HttpMethod.GET /
ERROR:robyn.logger:Port 8080 is already in use. Please use a different port.

### Your operating system

None

### Your Python version (`python --version`)

None

### Your Robyn version

None

**Comment by VishnuSanal** [comment]
I'm working on this (#857)

**Comment by sansyrox** [comment]
@VishnuSanal , we will need a new PR for this, right?
