### ISSUE TITLE
robyn --deploy

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#869]
This new feature would enable users to deploy their source code directly to a server. The deployment process would be configured through a robyn.yaml file, specifying crucial deployment details.

Key aspects of the proposed feature include:

Configuration via robyn.yaml: This file would contain the server's destination details, primarily the IP address of the Virtual Private Server (VPS).

Deployment to Different Destinations:

- VPS Deployment: When deploying to a VPS, the robyn.yaml would specify the IP address. This approach would also require setting up a reverse proxy and SSL certificates, potentially using tools like Caddy to handle these aspects.
- Docker Deployment: If a Dockerfile exists in the project, the deployment destination could be an artifact repository (artifactory), where the Docker container would be hosted.

The proposal underscores the need for a flexible deployment solution that accommodates both traditional VPS hosting environments and modern containerized applications. This feature would significantly streamline the deployment process for Robyn users, making it easier to manage deployments across different environments.

**Comment by Nightmerp** [comment]
I'm working on this!

**Comment by sansyrox** [comment]
moved to a different repo.
