### ISSUE TITLE
A file serve Download bug.

### ISSUE THREAD

**Issue by asamaayako** [sparckles/Robyn#876]
### Bug Description

response a **.wav** file . The downloaded file is corrupted.   source size is 4.45 MB (4,671,364 bytes). but download file  has become 7.84 MB (8,229,002 bytes).
#### test code 
```python
import os
import pathlib

from robyn import Robyn, serve_file

app = Robyn(__name__)

current_file_path = pathlib.Path(__file__).parent.resolve()


@app.get("/")
def hello_world():
    file_path = os.path.join(current_file_path, "source.wav")  #a audio file
    return serve_file(file_path)


if __name__ == "__main__":
    app.start()

```

### Your operating system

Windows

### Your Python version (`python --version`)

3.11

### Your Robyn version

latest

### Additional Info

the console output **Robyn version: 0.56.0**.  I just use  **pip** install this project

**Comment by sansyrox** [comment]
Hey @asamaayako 👋
Thanks for reporting this. I will investigate tonight 😊

**Comment by sansyrox** [comment]
Thanks for pointing out @asamaayako 😄 

Looks like I need to dive a bit deeper as well 😄

**Comment by sansyrox** [comment]
Hey @asamaayako 👋 

Looks like I found a way 😄

**Comment by sansyrox** [comment]
I will be releasing 0.56.2 in a while. Could you test again?

**Comment by asamaayako** [comment]
error log look like this. 
```
INFO:robyn.logger: Starting server at http://127.0.0.1:8080[0m
INFO:actix_server.builder:starting 1 workers
INFO:actix_server.server:Actix runtime found; starting in Actix runtime
thread 'actix-rt|system:0|arbiter:0' panicked at src\types\response.rs:72:14:
called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [82, 73, 70,   
..  some bytes data 
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], error: Utf8Error { valid_
up_to: 4, error_len: Some(1) } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 
```
and request not response
