### ISSUE TITLE
CLI in documentation includes --port which doesn't work

### ISSUE THREAD

**Issue by Nightmerp** [sparckles/Robyn#892]
### Bug Description

https://robyn.tech/documentation/example_app/deployment#deploying-the-application describes the command to deploy a Robyn application on the CLI as `python app.py --port 8000 --processes=n --workers=m`, but modifying the port in this argument does not change the port binded to by the application.

### Your operating system

None

### Your Python version (`python --version`)

None

### Your Robyn version

None

**Comment by sansyrox** [comment]
Hey @Nightmerp 👋 

Thanks for raising the issue. This a problem with the docs. Fixing this.
