### ISSUE TITLE
CTRL+C causes crash on mac

### ISSUE THREAD

**Issue by luqasz** [sparckles/Robyn#899]
Hi.

When running robyn with `python3 app.py` causes python to crash and generate mac os bug report.
```python3
fish: Job 1, 'python3 app.py' terminated by signal SIGABRT (Abort)
```

**Comment by sansyrox** [comment]
Hey @luqasz 👋 

Thanks for the issue. Could you share the code snippet in your `app.py`?

**Comment by sansyrox** [comment]
hey @luqasz , ctrl + c is supposed to kill the program 😅  What do you expect to happen here?

**Comment by luqasz** [comment]
> hey @luqasz , ctrl + c is supposed to kill the program 😅 What do you expect to happen here?

Gracefull shutdown. When I wrap fastapi app with `KeyboardInterrupt` I can intercept it and shutdown gracefully. With robyn I can't.

**Comment by sansyrox** [comment]
@luqasz , I see. So you expect an exception to surface, which you can handle.

This is definitely a bug. Will try to address it

**Comment by luqasz** [comment]
Thx.

**Comment by sansyrox** [comment]
Hey @luqasz 👋 

This has been fixed now 😄
