### ISSUE TITLE
Opentelemetry instrumentation

### ISSUE THREAD

**Issue by luqasz** [sparckles/Robyn#900]
Hi.

I'd like to add opentelemetry instrumentation into robyn. Robyn isn't a regular ASGI app `Robyn` class isn't callable. Thus it's not possible to use existing otel asgi instrumentator.

Instrumentator would have to hook into routing code, before executing given route function. 
Any ideas how to get inside robyn guts ?

**Comment by sansyrox** [comment]
Hey @luqasz 👋 

Robyn has a `app.before_request` method. Would that work?

**Comment by luqasz** [comment]
`app.before_request` is a decorator for each route ? If so then I'd have to implement it in each endpoint.
Ideally a generator / context manager would be best. OpenTelemetry sdk relies mostly on context [managers](https://opentelemetry-python.readthedocs.io/en/latest/api/trace.html#opentelemetry.trace.Tracer.start_as_current_span) for spans. For example:
```python
def before_request(route_handler):
    with tracer.start_as_current_span("before") as span:
        # add additional span context such as request ip, headers etc.
        # execute route handler
        route_handler()
```

**Comment by sansyrox** [comment]
> app.before_request is a decorator for each route ?
No, you can just use `app.before_request` and it will act like a global middleware.

**Comment by sansyrox** [comment]
@luqasz , let me know if that doesn't work well. I'll be happy to accommodate more changes

**Comment by sansyrox** [comment]
Closing this @luqasz . Feel free to reopen if you have any more questions 😄
