### ISSUE TITLE
Add get_headers declarations missing from Request

### ISSUE THREAD

**Issue by goSeeFuture** [sparckles/Robyn#905]
Add get_headers declarations missing from `Request`

- In a development proxy scenario, I need to get all fields at once to construct a request sent to an upstream server.
- ~~Can't get it through `get()`, `contains()`, `is_empty()` which are methods on `Request`.~~
- It would be better to have methods that return `dict` structures that take out all the request headers at once, so that they are compatible with common (requests, aiohttp, httpx) HTTP client libraries that need to be passed in as parameters and don't need to be processed again by the developer.

I found `get_headers()` are not in robyn.pyi, and it would be nice to have them clearly defined to reduce confusion for developers.

**Comment by sansyrox** [comment]
Hey @goSeeFuture 👋 

Does `request.headers` not work for you ? 😅

**Comment by sansyrox** [comment]
Hey @goSeeFuture 👋 

Robyn's request class doesn't follow the concept of `getters` i.e. no `get_headers` or `get_query_params` . You can use `request.headers.get_all()` to access all the headers in a particular request.

Feel free to open the issue if you have any questions 😄
