### ISSUE TITLE
After the interface service has been running for a while, thread 'actix-rt|system:0|arbiter:0' panicked at src/types/headers.rs:174:40

### ISSUE THREAD

**Issue by stevin-hong** [sparckles/Robyn#907]
Great project! After the interface service has been running for a while, the following error suddenly appears. How can I find more detailed error information?
error:
thread 'actix-rt|system:0|arbiter:0' panicked at src/types/headers.rs:174:40:
called `Result::unwrap()` on an `Err` value: ToStrError { _priv: () }
stack backtrace:
   0:     0x7f27a3c58d02 - <unknown>
   1:     0x7f27a3c80f0c - <unknown>
   2:     0x7f27a3c5622f - <unknown>
   3:     0x7f27a3c58ad4 - <unknown>
   4:     0x7f27a3c5a10b - <unknown>
   5:     0x7f27a3c59e63 - <unknown>
   6:     0x7f27a3c5a5ad - <unknown>
   7:     0x7f27a3c5a482 - <unknown>
   8:     0x7f27a3c591d6 - <unknown>
   9:     0x7f27a3c5a1b4 - <unknown>
  10:     0x7f27a393f905 - <unknown>
  11:     0x7f27a393fe03 - <unknown>
  12:     0x7f27a39c7448 - <unknown>
  13:     0x7f27a39c1f54 - <unknown>
  14:     0x7f27a3940115 - <unknown>
  15:     0x7f27a39b8afe - <unknown>
  16:     0x7f27a39a5c31 - <unknown>
Aborted (core dumped)

**Comment by sansyrox** [comment]
Hey @stevin-hong 👋

Could you please share a code snippet that causes this crash?

**Comment by sansyrox** [comment]
Hey @stevin-hong , try installing v0.58.1 . Your issue should be fixed 😄
