### ISSUE TITLE
bump watchdog to fix the compatibility with Python 3.12 on MacOS

### ISSUE THREAD

**Issue by haoxins** [sparckles/Robyn#912]
### Bug Description

Will get error when install Robyn on MacOS with Python 3.12

```
error: Failed to prepare distributions
  Caused by: Failed to fetch wheel: watchdog==2.2.1
  Caused by: Failed to build: `watchdog==2.2.1`
  Caused by: Build backend failed to build wheel through `build_wheel()` with exit status: 1
```

### Your operating system

MacOS

### Your Python version (`python --version`)

3.12

### Your Robyn version

latest

**Comment by sansyrox** [comment]
Hey @haoxins 👋 

Are you on an arm mac?

**Comment by haoxins** [comment]
> Hey @haoxins 👋
> 
> Are you on an arm mac?

no

**Comment by haoxins** [comment]
https://github.com/gorakhargosh/watchdog/blob/ab5117a9ddbd04e23bf9b703a3e1b7ef09490222/changelog.rst#400

watchdog supports 3.12 from v4?
