### ISSUE TITLE
SET COOKIE

### ISSUE THREAD

**Issue by paroxyste-0** [sparckles/Robyn#943]
### Bug Description

Hi, I tried to add a cookie, but I can't find it.

Does the set-cookie function add a cookie or does it modify the values in session?

How can I check and retrieve the cookie value because with request.headers I can't see it.

### Steps to Reproduce

Set my cookie

```python
@app.post('/auth/login')
async def auth_login(request: Request):
    response: Response = Response(headers={'Location': '/'}, description='OK', status_code=303)
    response.set_cookie(key='test_cookie', value='value_cookie')
    
    return response
```

My header after redirect to home route ('/')

with ```print(request.headers)``` i got :

`{"user-agent": ["Mozilla/5.0 (Windows NT 10.0; rv:127.0) Gecko/20100101 Firefox/127.0"], "dnt": ["1"], "sec-fetch-user": ["?1"], "connection": ["keep-alive"], "sec-gpc": ["1"], "accept-encoding": ["gzip, deflate, br, zstd"], "referer": ["http://127.0.0.1:8080/auth/login"], "priority": ["u=1"], "host": ["127.0.0.1:8080"], "accept-language": ["en-US,en;q=0.5"], "sec-fetch-mode": ["navigate"], "sec-fetch-site": ["same-origin"], "upgrade-insecure-requests": ["1"], "accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"], "cookie": ["session=eyJ1c2VyX2lkIjogImE4YzdjNmRhLTFlOTktNGViNy1iZGU4LTQ3OGYzYThkOTk0OSIsICJlbWFpbCI6ICJMQVVSRU5ULURFVkBUVVRBLklPIiwgImxvZ2dlZCI6IHRydWUsICJhZHMiOiAxLCAiZmF2b3JpdGUiOiAwLCAicGxhbiI6ICJGIn0=.ZscUTg.vVqahpp1j2j_iAAdLsnHfldbuCs"], "sec-fetch-dest": ["document"]}`

![image](https://github.com/user-attachments/assets/0c95bf0d-38a2-4a09-a35c-b295353660a5)

Were is it ?

Thanks for your help.

### Your operating system

Windows

### Your Python version (`python --version`)

3.12

### Your Robyn version

main branch

**Comment by sansyrox** [comment]
Hey @paroxyste-0 👋 

Thanks for raising the issue. Let me have a look tomorrow 😄

**Comment by sansyrox** [comment]
@paroxyste-0 , it is impossible to set set a cookie and redirect it a different path without interacting with the client regardless of the language or the framework . https://stackoverflow.com/questions/73135598/fastapi-redirectresponse-gets-message-forbidden-when-redirecting-to-a-dif/73137093#73137093

You will have to send it back to your client and then make another request.

I hope this was helpful. Feel free to reopen the issue if you need any more clarifications

**Comment by paroxyste-0** [comment]
Thank you for your answer,

On my login, when I make my post, I do have the fakesession return in my header, but then if I go to another page fakesession disappears from the header.

After POST
![image](https://github.com/user-attachments/assets/3f122e6b-24da-4bdb-9684-5aea8d5f982a)

After go to another link
![image](https://github.com/user-attachments/assets/39dc2658-ce5b-4c46-9fb7-02b1a1e7c1f6)

Do I have to modify all the responses to be able to keep it?

It's a pity that we can't put the values directly in the session as flask or starlette allow with session['my_key'] = 'my_value'.

Thanks for your reply.

**Comment by sansyrox** [comment]
Ah, so that is a different feature request. You are requesting `session` to be added in Robyn. Let me open a feature request for now

**Comment by paroxyste-0** [comment]
Thanks a lot

**Comment by bzar** [comment]
I ran into this as well, and I think the issue is that [set_cookie does not set a cookie, but a header](https://github.com/sparckles/Robyn/blob/12d8c0b9f1b43fd04198f2e288486c71d286191d/src/types/response.rs#L161-L167).

In order to set a cookie it should use a `Set-Cookie` header as outlined [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies). To make the current implementation actually set a cookie you need to call it something like `response.set_cookie(key="Set-Cookie", value=f"{cookie_name}={cookie_value}")`.

**Comment by sansyrox** [comment]
Hey @bzar 👋 

> The Cookie HTTP request header contains stored [HTTP cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies) associated with the server (i.e. previously sent by the server with the [Set-Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) header or set in JavaScript using [Document.cookie](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie)).

Read this - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie


A cookie is a special headers

**Comment by bzar** [comment]
Look, I'm not going to argue with you about how the cookie mechanism works. I'll just say it's more than just the Cookie-header. It works using HTTP headers but it has special handling in browsers so that the client doesn't need to handle resending the `Cookie` header every request.

As a user, I expect a `set_cookie` on a response object to work like in any other server framework, like [starlette](https://github.com/encode/starlette/blob/master/starlette/responses.py#L85-L122) (the framework behind FastAPI). You can look at any big framework that has this method for reference.

**Comment by dave42w** [comment]
> Hi, I'd like to try to take on this task if you'll let me This one seems like a good first issue

That sounds great to me. I'm a pretty new contributor to Robyn, happy to help if I can.

**Comment by sansyrox** [comment]
Hey @sarvensis ,

What would you like to do here specifically? Thanks for the support @dave42w 😄

**Comment by sarvensis** [comment]
Hi. Thank you for your responses!
I was planning to add the following optional attributes:
- Expires;
- Max-Age;
- Secure;
- HttpOnly;
- Domain;
- Path;
- SameSite.

And reflect these changes in documentation and tests.
