### ISSUE TITLE
feat: override openapi json

### ISSUE THREAD

**Issue by VishnuSanal** [sparckles/Robyn#961]
let the user override the openapi json file. refrain from generating, if:

a) the file is present somewhere, OR
b) the user passes it as a param to Robyn()

**Comment by sansyrox** [comment]
@VishnuSanal , let us restrict the file only to the root of the project for this.

**Comment by sansyrox** [comment]
a) restrict the file to the root.
b) and override based on the path provided by the user.

Give priority to b over a in case of a clash.

@VishnuSanal , can you please have a look at this?

**Comment by VishnuSanal** [comment]
- check how fastapi does this

**Comment by sansyrox** [comment]
Hey @VishnuSanal ,

I've give the implementation a lot of thought. Here's what we should do

1. Restrict the OpenAPI JSON file to the root: This rule ensures consistency and simplifies file location, making debugging easier.

2. Allow users to override the OpenAPI JSON by passing a file path: Users who want custom configurations can pass their own file path via a parameter to Robyn(). If the file is passed as a parameter, it takes priority over the root file, ensuring flexibility.

3. Resolve potential conflicts: In case both options (root file and file passed as a parameter) exist, give priority to the user-passed path, as you suggested.

**Comment by VishnuSanal** [comment]
alright, will do this. btw, I still think placing a file with a certain name in a certain path feels an "old" approach of doing things. (it reminds me of running windows xp 🙈). but, let's agree to disagree!

**Comment by sansyrox** [comment]
> alright, will do this. btw, I still think placing a file with a certain name in a certain path feels an "old" approach of doing things.

I can see you haven't written any next js code 🤷 . This is a very common pattern in modern web dev. (https://nextjs.org/docs/pages/building-your-application/routing )

We also a follow a similar pattern in starfyre.
