### ISSUE TITLE
`app.set_response_header`will break Openapi doc rendering

### ISSUE THREAD

**Issue by kigawas** [sparckles/Robyn#976]
### Bug Description

`app.set_response_header("Content-Type", "application/json")` will add additional content type to `/docs` endpoint, which can disable browsers to render the html content.

This can be fixed by prioritizing the content type in response (around https://github.com/sparckles/Robyn/blob/main/src/types/headers.rs#L161)

### Steps to Reproduce

```py
from pydantic import BaseModel
from robyn import Request, Robyn

app = Robyn(__file__)

app.set_response_header("Content-Type", "application/json")


class Response(BaseModel):
    text: str


@app.get("/")
async def h(request: Request):
    return Response(text="hello")


app.start(port=8080)
```

Then you'll see:

<img width="1039" alt="image" src="https://github.com/user-attachments/assets/345b0fd4-720f-4fac-9795-de4d830e45a0">

```
$ curl -v http://localhost:8080/docs/
...
> Host: localhost:8080
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< content-length: 938
< content-type: text/html
< content-type: application/json
< date: Sun, 06 Oct 2024 10:56:04 GMT
...
```

### Your operating system

None

### Your Python version (`python --version`)

None

### Your Robyn version

latest

**Comment by sansyrox** [comment]
@VishnuSanal , could you have a look here.

**Comment by sansyrox** [comment]
Thank you for raising the issue @kigawas , we are having a look 😄
