### ISSUE TITLE
Fix Vercel CI failing on every PR when it really is waiting to get an approval

### ISSUE THREAD

**Issue by VishnuSanal** [sparckles/Robyn#984]
it is annoying when all the tests pass & still we see the red cross next to the commits, cuz the vercel deployment was waiting to get an approval.

add a mechanism to either:

- do not report waiting for approval as "failed" workflow.
- wait for it to get approved, skip running unless explicitly triggered.
- run it every time.

listed on the order of priority (my suggesion). @sansyrox what do you think?

also, follow up: I don't see any workflow files inside `.github/workflows/`. how are we triggering the workflow runs?

**Comment by sansyrox** [comment]
This is fixed now 😉
