### ISSUE TITLE
Robyn not running on OS X

### ISSUE THREAD

**Issue by amdescombes** [sparckles/Robyn#986]
### Bug Description

Hi everybody,
First of all, congratulations on your great work.
I'm trying to test Robyn on an OS X (Macbook pro M4 Pro, latest Sequoia OS X, Python3.11) environment in order to compare it to Sanic. 
I'm getting an invalid port error, sanic runs fine on the same port.
Is there a known issue with OS X?
Thanks in advance
André

### Steps to Reproduce

# hello world program:

from robyn import Robyn

# Create an instance of Robyn app
app = Robyn(__file__)

# Define a basic route
@app.get("/")
async def home():
    return "Hello World!"

# Start the Robyn server
if __name__ == "__main__":
    app.start(port=8081)

### Your operating system

MacOS

### Your Python version (`python --version`)

3.11

### Your Robyn version

latest

### Additional Info

I'd be happy to do some testing

**Comment by sansyrox** [comment]
Hey @amdescombes 👋 

It does work for me. Could you send me the response of `lsof -i tcp:8081` from your terminal?

**Comment by amdescombes** [comment]
Hi @sansyrox,
lsof -i tcp:8081
does not return anything
and when I run a Sanic Hello World program on the same port it works fine!
Thanks

**Comment by amdescombes** [comment]
Here's the exception I get:

Traceback (most recent call last):
  File "/Users/amdescombes/Desktop/Desktop - Andre’s MacBook Pro/AMD/BinanceTest/testrobyn.py", line 13, in <module>
    app.start(port=8081)
  File "/opt/homebrew/lib/python3.9/site-packages/robyn/__init__.py", line 257, in start
    while self.is_port_in_use(port):
  File "/opt/homebrew/lib/python3.9/site-packages/robyn/__init__.py", line 225, in is_port_in_use
    raise Exception(f"Invalid port number: {port}")
Exception: Invalid port number: 8081

**Comment by sansyrox** [comment]
Hey @amdescombes 👋 

What command are you using to run the script?

**Comment by amdescombes** [comment]
I'm running like so (I pass no arguments to it):

python3.11 testrobyn.py

**Comment by amdescombes** [comment]
Are you running on an Intel or an Apple processor @sansyrox ?
I tried running on Python3.9 and it didn't work either

**Comment by sansyrox** [comment]
@amdescombes , I am running on an apple processor.

**Comment by sansyrox** [comment]
@VishnuSanal , can you try once?

**Comment by sansyrox** [comment]
@amdescombes , could you please share a github gist of the code?

**Comment by amdescombes** [comment]
Hi @sansyrox here is the requested code:

`
from robyn import Robyn

app = Robyn(__file__)

@app.get("/")
async def home():
    return "Hello, Robyn!"

if __name__ == "__main__":
    app.start(port=8081)
`

**Comment by amdescombes** [comment]
That is the code that doesn't work

**Comment by sansyrox** [comment]
Hey @amdescombes 👋 

I am unable to replicate the bug. Can you share your mac os version?

**Comment by amdescombes** [comment]
Yes, I'm running on Macbook Pro M3 Max with Sequoia 15.0.1 (24A348)

**Comment by amdescombes** [comment]
what's strange is that I can open the same port with CherryPy, Flask or Sanic with no problems

**Comment by sansyrox** [comment]
@amdescombes , is port 8080 or 8082 working?

**Comment by amdescombes** [comment]
Yessss

**Comment by amdescombes** [comment]
Thanks, it must be something with 8081

**Comment by sansyrox** [comment]
Alright, then. Closing.
