### ISSUE TITLE
Robyn doesn't contain documentation for using rust directly in a python codebase

### ISSUE THREAD

**Issue by sansyrox** [sparckles/Robyn#988]
Add it.

https://github.com/sparckles/Robyn/blob/main/integration_tests/random_number.rs

You can see how this function is being imported in the folder

**Comment by sansyrox** [comment]
@VishnuSanal , can you have a look here?

**Comment by VishnuSanal** [comment]
I didn't quite get this. can you give me an example? that file/function is not used anywhere it seems

**Comment by VishnuSanal** [comment]
it does! ref: https://robyn.tech/documentation/api_reference/using_rust_directly
