### ISSUE TITLE
Preview Release CI fails on linux-cross

### ISSUE THREAD

**Issue by VishnuSanal** [sparckles/Robyn#990]
fails here (https://github.com/sparckles/Robyn/actions/runs/11433204331/job/31804822966?pr=989)

upstream issue thread ref: https://github.com/uraimo/run-on-arch-action/issues/155

**Comment by sansyrox** [comment]
@VishnuSanal , any update here? It feels like the bug has been fixed.

**Comment by VishnuSanal** [comment]
I have updated #977 -- let's see whether it passes.

**Comment by VishnuSanal** [comment]
> any update here? It feels like the bug has been fixed.
> > I have updated #977 -- let's see whether it passes.

seems like not, the tests still fail.
